[package]
name = "aa4c-transfer"
description = "AA4C 传输引擎：ATP 协议、文件收发、哈希校验"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
aa4c-types = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
