-- 每任务下载选项（对标 Motrix 新建任务对话框的"高级选项"，DOWNLOAD_DESIGN.md §5/§10）。
--
-- 为什么要落库而不是只在内存里传一次：`retry()` 对 HTTP 任务是"删旧记录 + 用原
-- URL 重新添加"（aria2 没有复活同一个 GID 的能力），不存这些选项的话重试就会
-- 丢掉 referer/cookie/保存位置/文件名——而"从挑剔的站点重试一个失败下载"恰恰
-- 是最需要这些选项的场景，丢了等于重试必然再失败一次。
--
-- 存成一个 JSON 列而不是拆四个列：这些字段是"引擎无关请求描述"的一部分
-- （DOWNLOAD_DESIGN.md §10 预留给插件系统的接缝），将来插件可能再加字段，
-- 每次都做一次 ALTER TABLE 不划算；且它们只被整体读写、从不参与查询条件，
-- 没有拆列的收益。NULL = 这条任务没有任何自定义选项（绝大多数任务）。
ALTER TABLE download_tasks ADD COLUMN options TEXT;
