[package]
name = "aa4c-core"
description = "AA4C Core：生命周期、事件总线、服务编排"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
aa4c-types = { workspace = true }
aa4c-proto = { workspace = true }
aa4c-identity = { workspace = true }
aa4c-discovery = { workspace = true }
aa4c-transfer = { workspace = true }
aa4c-store = { workspace = true }
aa4c-download = { workspace = true }
blake3 = { workspace = true }
notify-debouncer-mini = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dirs = { workspace = true }
hostname = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
bs58 = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
aa4c-server = { workspace = true }
tracing-subscriber = { workspace = true }
